const time = new Date(); 
let display = time;
var rng = new RNG(time.getTime()+191701321413612813719782722022200);  
const submit = document.getElementById("submit");
const edit = document.getElementById("edit");
const copy = document.getElementById("copy");
const timer = ms => new Promise(res => setTimeout(res, ms));
const pleasefill = document.getElementById("pleasefill");

async function load () {
 $("#resultscard1").slideDown() 
 $("#resultscard2").slideDown()
 $("#resultscard3").slideDown() 
 $("#resultscard4").slideDown()
 await timer(300)
 $("#S1").animate({opacity: 1}, 200);
 $("#S2").animate({opacity: 1}, 200);
 $("#S3").animate({opacity: 1}, 200);
 $("#S4").animate({opacity: 1}, 200);
 await timer(200);
 submit.disabled = false;
 copy.disabled = false;
$("#nameS1").prop("disabled", false);
 $("#nameS2").prop("disabled", false);
 $("#nameS3").prop("disabled", false);
 $("#nameS4").prop("disabled", false);
  }
async function unload() {
submit.disabled = true;
copy.disabled = true;
 $("#nameS1").prop("disabled", true);
 $("#nameS2").prop("disabled", true);
 $("#nameS3").prop("disabled", true);
 $("#nameS4").prop("disabled", true);
 $("#S1").animate({opacity: 0}, 200);
 $("#S2").animate({opacity: 0}, 200);
 $("#S3").animate({opacity: 0}, 200);
 $("#S4").animate({opacity: 0}, 200);
 $("#resultscard1").slideUp()
 $("#resultscard2").slideUp()
 $("#resultscard3").slideUp()
 $("#resultscard4").slideUp()
  }
submit.onclick = async function() 
{
    display = new Date();
    roll();
}
async function roll()
{
    unload();
    await timer(300);
    let array = [1, 2, 3, 4];
    var i, j, k;
    let end = rng.random(50, 360);
    for (k=1; k<=end; k++)
    {
        for (i = 3; i > 1; i--) {
        j = rng.random(0, i);
        [array[i], array[j]] = [array[j], array[i]];
         }
        j = rng.random(0, 3);
        [array[0], array[j]] = [array[j], array[0]];
    }
    for (i = 0; i < 4; i++)
    {
        let n = array[i];
        document.getElementById("S"+(i+1)).innerHTML=document.getElementById("nameS"+n).value;
    } 
    await timer(500);
    load();
}
  copy.onclick = function () {
    const S1 = document.getElementById("S1").innerHTML;
    const S2 = document.getElementById("S2").innerHTML;
    const S3 = document.getElementById("S3").innerHTML;
    const S4 = document.getElementById("S4").innerHTML;
    navigator.clipboard.writeText(
    "Generated by ORR v4.0.1 at " + display.toLocaleString("vi-VN") 
    + "\nS1: " +S1
    + "\nS2: " +S2
    + "\nS3: " +S3
    + "\nS4: " +S4);
  }
